# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-25 17:29
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_locationtrip'),
    ]

    operations = [
        migrations.AddField(
            model_name='location',
            name='created_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='locationtrip',
            name='created_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='trip',
            name='created_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
